# Generated by Django 4.2.5 on 2023-10-01 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ThumbnailSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("include_original_link", models.BooleanField(default=False)),
                ("generate_expiring_link", models.BooleanField(default=False)),
                (
                    "thumbnail_sizes",
                    models.ManyToManyField(to="image_upload_app.thumbnailsize"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                (
                    "thumbnail_200",
                    models.ImageField(
                        blank=True, null=True, upload_to="thumbnails/200/"
                    ),
                ),
                (
                    "thumbnail_400",
                    models.ImageField(
                        blank=True, null=True, upload_to="thumbnails/400/"
                    ),
                ),
                (
                    "original_image",
                    models.ImageField(blank=True, null=True, upload_to="originals/"),
                ),
                ("expiring_link", models.URLField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
