# Generated by Django 4.2.5 on 2023-10-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_upload_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="level",
            field=models.CharField(
                choices=[
                    ("BASIC", "Basic"),
                    ("PREMIUM", "Premium"),
                    ("ENTERPRISE", "Enterprise"),
                ],
                default="BASIC",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
